
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Andreia
 */
public class UsuariosTela extends javax.swing.JFrame {

    /**
     * Creates new form UsuariosTela
     */
    public UsuariosTela() {
        super("Usuarios");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuariosPanel = new javax.swing.JPanel();
        nomeTextField = new javax.swing.JTextField();
        senhaTextField = new javax.swing.JTextField();
        tipoUsuarioComboBox = new javax.swing.JComboBox<>();
        preferenciaLivro1ComboBox = new javax.swing.JComboBox<>();
        preferenciaLivro2ComboBox = new javax.swing.JComboBox<>();
        livroPreferido1Label = new javax.swing.JLabel();
        livroPreferido2Label = new javax.swing.JLabel();
        cadastrarUsuarioButton = new javax.swing.JButton();
        alterarUsuarioButton = new javax.swing.JButton();
        removerUsuarioButton = new javax.swing.JButton();
        cancelarUsuarioButton = new javax.swing.JButton();
        consultarUsuarioButton = new javax.swing.JButton();
        mostrarLivrosButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usuariosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Gerenciamento de usuários"));

        nomeTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite seu login"));

        senhaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite sua senha"));

        tipoUsuarioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "comum" }));
        tipoUsuarioComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoUsuarioComboBoxActionPerformed(evt);
            }
        });

        preferenciaLivro1ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nao tem", "Ciencias e Sociedade", "Sustentabilidade", "Tecnologia" }));
        preferenciaLivro1ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferenciaLivro1ComboBoxActionPerformed(evt);
            }
        });

        preferenciaLivro2ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nao tem", "Ciencias e Sociedade", "Sustentabilidade", "Tecnologia" }));

        livroPreferido1Label.setText("Tipo livro preferido 1");

        livroPreferido2Label.setText("Tipo livro preferido 2");

        cadastrarUsuarioButton.setText("Cadastrar");
        cadastrarUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarUsuarioButtonActionPerformed(evt);
            }
        });

        alterarUsuarioButton.setText("Alterar");
        alterarUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarUsuarioButtonActionPerformed(evt);
            }
        });

        removerUsuarioButton.setText("Remover");
        removerUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerUsuarioButtonActionPerformed(evt);
            }
        });

        cancelarUsuarioButton.setText("Cancelar");
        cancelarUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarUsuarioButtonActionPerformed(evt);
            }
        });

        consultarUsuarioButton.setText("Consultar");
        consultarUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarUsuarioButtonActionPerformed(evt);
            }
        });

        mostrarLivrosButton.setText("Mostrar Livros");
        mostrarLivrosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarLivrosButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usuariosPanelLayout = new javax.swing.GroupLayout(usuariosPanel);
        usuariosPanel.setLayout(usuariosPanelLayout);
        usuariosPanelLayout.setHorizontalGroup(
            usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usuariosPanelLayout.createSequentialGroup()
                        .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tipoUsuarioComboBox, 0, 338, Short.MAX_VALUE)
                            .addComponent(senhaTextField)
                            .addComponent(nomeTextField))
                        .addGap(14, 14, 14)
                        .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(preferenciaLivro2ComboBox, 0, 241, Short.MAX_VALUE)
                            .addComponent(preferenciaLivro1ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(usuariosPanelLayout.createSequentialGroup()
                                .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(livroPreferido1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(livroPreferido2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 47, Short.MAX_VALUE)))
                        .addGap(23, 23, 23))
                    .addGroup(usuariosPanelLayout.createSequentialGroup()
                        .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(usuariosPanelLayout.createSequentialGroup()
                                .addComponent(cadastrarUsuarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(alterarUsuarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(usuariosPanelLayout.createSequentialGroup()
                                .addComponent(consultarUsuarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mostrarLivrosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removerUsuarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelarUsuarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        usuariosPanelLayout.setVerticalGroup(
            usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(usuariosPanelLayout.createSequentialGroup()
                        .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(senhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(usuariosPanelLayout.createSequentialGroup()
                        .addComponent(livroPreferido1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(preferenciaLivro1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(livroPreferido2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usuariosPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(preferenciaLivro2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tipoUsuarioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cadastrarUsuarioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(alterarUsuarioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removerUsuarioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usuariosPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(mostrarLivrosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cancelarUsuarioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consultarUsuarioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usuariosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usuariosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarLivrosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarLivrosButtonActionPerformed
     try {
        String resultado = LivroDAO.listarLivrosComoTexto();
        if (resultado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum livro encontrado.");
        } else {
            JOptionPane.showMessageDialog(this, resultado);
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erro ao listar livros: " + e.getMessage());
    }
              // TODO add your handling code here:
    }//GEN-LAST:event_mostrarLivrosButtonActionPerformed

    private void consultarUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarUsuarioButtonActionPerformed
        String nome = nomeTextField.getText();
        String senha = senhaTextField.getText();

        Usuario usuario = new Usuario(nome, senha);
        try {
            if (UsuarioDAO.consultaUsuario(usuario)) {
                tipoUsuarioComboBox.setSelectedItem(usuario.getTipo());
                if (usuario.getTipo().equals("comum")) {
                    preferenciaLivro1ComboBox.setSelectedItem(usuario.getPreferenciaLivro1());
                    preferenciaLivro2ComboBox.setSelectedItem(usuario.getPreferenciaLivro2());
                } else {
                    preferenciaLivro1ComboBox.setSelectedIndex(0);
                    preferenciaLivro2ComboBox.setSelectedIndex(0);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Usuario nao cadrastado", "Ups", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problemas Tecnicos", "Ups", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_consultarUsuarioButtonActionPerformed

    private void cancelarUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarUsuarioButtonActionPerformed
        //DashboardTela dt = new DashboardTela(null);
        LoginTela lt = new LoginTela();
        lt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarUsuarioButtonActionPerformed

    private void alterarUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarUsuarioButtonActionPerformed
        String nome = nomeTextField.getText();
        String senha = senhaTextField.getText();
        String tipo = (String) tipoUsuarioComboBox.getSelectedItem();

        Usuario u = new Usuario();
        u.setNome(nome);
        u.setSenha(senha);
        u.setTipo(tipo);

        if (tipo.equals("comum")) {
            String preferenciaLivro1 = (String) preferenciaLivro1ComboBox.getSelectedItem();
            String preferenciaLivro2 = (String) preferenciaLivro2ComboBox.getSelectedItem();
            u.setPreferenciaLivro1(preferenciaLivro1);
            u.setPreferenciaLivro2(preferenciaLivro2);
        }

        try {
            UsuarioDAO.alterarUsuario(u);
            JOptionPane.showMessageDialog(this, "Usuário "  + nomeTextField.getText() +" alterado com sucesso!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao alterar o usuário: " + e.getMessage());
        }


    }//GEN-LAST:event_alterarUsuarioButtonActionPerformed

    private void cadastrarUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarUsuarioButtonActionPerformed
        String nome = nomeTextField.getText();
        String senha = senhaTextField.getText();
        String tipo = tipoUsuarioComboBox.getItemAt(tipoUsuarioComboBox.getSelectedIndex());
        String preferencia1 = (String) preferenciaLivro1ComboBox.getSelectedItem();
        String preferencia2 = (String) preferenciaLivro2ComboBox.getSelectedItem();

        Usuario usuario = new Usuario(nome, senha, tipo, preferencia1, preferencia2);
        try {
            UsuarioDAO.cadastraUsuario(usuario);
            JOptionPane.showMessageDialog(null, "Usuario: " + nomeTextField.getText() + " cadastrado com sucesso");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Usuario: " + nomeTextField.getText() + " ja está cadastrado", "ups ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cadastrarUsuarioButtonActionPerformed

    private void tipoUsuarioComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoUsuarioComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoUsuarioComboBoxActionPerformed

    private void removerUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerUsuarioButtonActionPerformed

    String nome = JOptionPane.showInputDialog(this, "Digite o nome do usuario que deseja remover:");

    if (nome != null && !nome.trim().isEmpty()) {
        try {
            boolean removido = UsuarioDAO.removerUsuario(nome);
            if (removido) {
                JOptionPane.showMessageDialog(this, "usuario " +nome+" removido  com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "usuario não encontrado.");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao remover usuario: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "usuario "+nome+" inválido.");
    }


    }//GEN-LAST:event_removerUsuarioButtonActionPerformed

    private void preferenciaLivro1ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferenciaLivro1ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preferenciaLivro1ComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuariosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuariosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuariosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuariosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuariosTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarUsuarioButton;
    private javax.swing.JButton cadastrarUsuarioButton;
    private javax.swing.JButton cancelarUsuarioButton;
    private javax.swing.JButton consultarUsuarioButton;
    private javax.swing.JLabel livroPreferido1Label;
    private javax.swing.JLabel livroPreferido2Label;
    private javax.swing.JButton mostrarLivrosButton;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JComboBox<String> preferenciaLivro1ComboBox;
    private javax.swing.JComboBox<String> preferenciaLivro2ComboBox;
    private javax.swing.JButton removerUsuarioButton;
    private javax.swing.JTextField senhaTextField;
    private javax.swing.JComboBox<String> tipoUsuarioComboBox;
    private javax.swing.JPanel usuariosPanel;
    // End of variables declaration//GEN-END:variables
}
